<%
  db_url = ENV['CINELAR_DB_URL']
  if db_url
    uri = URI.parse(db_url)
    db_name = uri.path.delete('/')
    db_host = uri.host
    db_port = uri.port || 5432
    db_user = uri.user || 'cinelar'
    db_pass = uri.password || 'cinelar'
  else
    db_name = ENV['CINELAR_DB'] || 'cinelar'
    db_host = ENV['CINELAR_DB_HOSTNAME'] || 'localhost'
    db_user = ENV['CINELAR_DB_USERNAME'] || 'cinelar'
    db_pass = ENV['CINELAR_DB_PASSWORD'] || 'cinelar'
    db_port = ENV['CINELAR_DB_PORT'] || 5432
  end
%>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  sslmode: <%= ENV['CINELAR_DB_SSL_MODE'] || 'prefer' %>

development:
  <<: *default
  database: <%= db_name %>
  host: <%= db_host %>
  username: <%= db_user %>
  password: <%= db_pass %>
  port: <%= db_port %>

test:
  <<: *default
  database: <%= db_name %>_test
  host: <%= db_host %>
  username: <%= db_user %>
  password: <%= db_pass %>
  port: <%= db_port %>

production:
  <<: *default
  database: <%= db_name %>
  host: <%= db_host %>
  username: <%= db_user %>
  password: <%= db_pass %>
  port: <%= db_port %>

