---
general:
  site_name:
    client: true
    exposed_to_client: true
    refresh: true
    default: CinelarTV
    min: 1
    max: 50
    regex: ^[a-zA-Z0-9 ]*$
  site_logo:
    client: true
    refresh: true
    default: /assets/default/cinelartv_default_logo.svg
    type: 'image'
  site_mobile_logo:
    client: true
    refresh: true
    default: /assets/default/cinelartv_default_logo.png
    type: 'image'
  site_favicon:
    client: true
    refresh: true
    default: /assets/default/cinelartv_default_favicon.png
    type: 'image'
  site_description:
    client: true
    refresh: true
    default: CinelarTV
    min: 1
    max: 50
    regex: ^[a-zA-Z0-9 ]*$
  default_locale:
    client: true
    refresh: true
    default: es
    validator: "AllowedValuesValidator"
    type: 'enum'
    allowed_values:
      - en
      - es
      - pt
  enable_splash_screen:
    client: true
    refresh: false
    default: true
    type: 'boolean'
  allow_registration:
    client: true
    refresh: true
    default: true
    type: 'boolean'
  base_url:
    client: true
    refresh: true
    readonly: true,
    hidden: true
  enable_sitemap:
    client: true
    refresh: false
    default: true
    type: 'boolean'
security:
  allow_admin_to_create_users:
    client: true
    refresh: true
    default: false
    hidden: true
    type: 'boolean'  
content:
  enable_metadata_recommendation:
    client: true
    refresh: true
    default: true
    type: 'boolean'
  tmdb_api_key:
    client: false
    refresh: false
    default: ""
    type: 'string'
    secret: true

player:
  enable_chromecast:
    client: true
    refresh: true
    default: true
    type: 'boolean'
  additonal_player_settings:
    client: true
    refresh: true
    default: "{}"
    type: 'code'

monetization:
  enable_subscription:
    client: true
    refresh: true
    default: false
    type: 'boolean'

  lemon_api_key:
    client: false
    refresh: true
    default: ""
    type: 'string'
    secret: true

  lemon_webhook_secret:
    client: false
    refresh: true
    default: ""
    type: 'string'
    secret: true

storage:
  storage_provider:
    client: true
    refresh: true
    default: local
    type: 'enum'
    allowed_values:
      - local
      - s3
  s3_access_key_id:
    client: false
    refresh: true
    default: ""
    type: 'string'
    secret: true
  s3_secret_access_key:
    client: false
    refresh: true
    default: ""
    type: 'string'
    secret: true
  s3_bucket:
    client: true
    refresh: true
    default: ""
    type: 'string'
    secret: false
  s3_region:
    client: true
    refresh: true
    default: "us-east-1"
    type: 'enum'
    allowed_values:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - ap-east-1
      - ap-south-1
      - ap-northeast-2
      - ap-southeast-1
      - ap-southeast-2
      - ap-northeast-1
      - ca-central-1
      - cn-north-1
      - cn-northwest-1
      - eu-central-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-north-1
      - me-south-1
      - sa-east-1
  s3_endpoint:
    client: true
    refresh: true
    default: ""
    type: 'string'
    secret: false
  cdn_url:
    client: true
    refresh: true
    default: ""
    type: 'string'
    secret: false
  cdn_enabled:
    client: true
    refresh: true
    default: false
    type: 'boolean'

customization:
  enable_carousel:
    client: true
    refresh: true
    default: true
    type: 'boolean'
  homescreen_cards_style:
    client: true
    refresh: true
    default: "CinelarTV"
    type: 'enum'
    allowed_values:
      - poster
      - backdrop
      - CinelarTV
      - custom_html
  homescreen_cards_custom_html:
    client: true
    refresh: true
    default: ""
    type: 'code'
  background_color:
    client: true
    refresh: true
    default: "#000000"
    type: 'color'
  body_text_color:
    client: true
    refresh: true
    default: "#ffffff"
    type: 'color'
  header_background_color:
    client: true
    refresh: true
    default: "#000000"
    type: 'color'
  base_font_family:
    client: true
    refresh: true
    default: Jost*
  header_font_family:
    client: true
    refresh: true
    default: Jost*
  primary_color:
    client: true
    refresh: true
    default: "#181818FF"
    type: 'color'
  secondary_color:
    client: true
    refresh: true
    default: "#181818FF"
    type: 'color'
  tertiary_color:
    client: true
    refresh: true
    default: "#0084F0FF"
    type: color
  quaternary_color:
    client: true
    refresh: true
    default: rgba(255, 255, 255, 0.2)
    type: color
  custom_css:
    client: false # Javascript don't need to read it, because it's rendered on a <style> tag
    refresh: true
    default: ""
    type: 'code'
  additional_icons:
    client: true
    refresh: true
    default: ""
    type: 'list'
  
developer:
  enable_js_error_reporting:
    client: true
    refresh: true
    default: true
    type: 'boolean'
  api_custom_data:
    client: true
    refresh: false
    default: "{}"
    type: 'code'
    secret: false
experimental:
  enable_web_updater:
    client: true
    refresh: true
    default: false
    type: 'boolean'
  external_stylesheets:
    client: true
    refresh: true
    default: https://fonts.cdnfonts.com/css/jost
    type: 'list'
  external_scripts:
    client: true
    refresh: true
    default: ""
    type: 'list'
  custom_js:
    client: true
    refresh: true
    default: ""
    type: 'code'
  enable_custom_pages:
    client: true
    refresh: true
    default: false
    type: 'boolean'
  enable_plugins:
    client: true
    refresh: true
    default: false
    type: 'boolean'

internal:
  license_key:
    client: false
    refresh: true
    default: ""
    type: 'string'
    secret: true
    hidden: true # It's setted on the wizard
  wizard_completed:
    client: true # Frontend can read it because it's used to show the wizard or banner
    refresh: true
    default: false
    type: 'boolean'
    hidden: true # Internal use only
