---
general:
  site_name:
    client: true
    exposed_to_client: true
    refresh: true
    default: CinelarTV
    min: 1
    max: 50
    regex: ^[a-zA-Z0-9 ]*$
  site_logo:
    client: true
    refresh: true
    default: /assets/default/cinelartv_default_logo.svg
    type: 'image'
  site_description:
    client: true
    refresh: true
    default: CinelarTV
    min: 1
    max: 50
    regex: ^[a-zA-Z0-9 ]*$
  default_locale:
    client: true
    refresh: true
    default: es
    validator: "AllowedValuesValidator"
    type: 'enum'
    allowed_values:
      - en
      - es
      - pt
  enable_splash_screen:
    client: true
    refresh: true
    default: true
    type: 'boolean'
  allow_registration:
    client: true
    refresh: true
    default: true
    type: 'boolean'
  base_url:
    client: true
    refresh: true
    readonly: true,
    hidden: true
content:
  tmdb_api_key:
    client: false
    refresh: true
    default: ""
    type: 'string'
    secret: true
  
storage:
  allow_video_direct_link:
    client: true
    refresh: true
    default: false
    type: 'boolean'
  storage_provider:
    client: true
    refresh: true
    default: local
    type: 'enum'
    allowed_values:
      - local
      - s3
  s3_access_key_id:
    client: false
    refresh: true
    default: ""
    type: 'string'
    secret: true
  s3_secret_access_key:
    client: false
    refresh: true
    default: ""
    type: 'string'
    secret: true
  s3_bucket:
    client: true
    refresh: true
    default: ""
    type: 'string'
    secret: false
  s3_region:
    client: true
    refresh: true
    default: "us-east-1"
    type: 'enum'
    allowed_values:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - ap-east-1
      - ap-south-1
      - ap-northeast-2
      - ap-southeast-1
      - ap-southeast-2
      - ap-northeast-1
      - ca-central-1
      - cn-north-1
      - cn-northwest-1
      - eu-central-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-north-1
      - me-south-1
      - sa-east-1
  s3_endpoint:
    client: true
    refresh: true
    default: ""
    type: 'string'
    secret: false


customization:
  enable_carousel:
    client: true
    refresh: true
    default: true
    type: 'boolean'
  homescreen_cards_style:
    client: true
    refresh: true
    default: "CinelarTV"
    type: 'enum'
    allowed_values:
      - poster
      - backdrop
      - CinelarTV
      - custom_html
  homescreen_cards_custom_html:
    client: true
    refresh: true
    default: ""
    type: 'code'
  background_color:
    client: true
    refresh: true
    default: "#000000"
    type: 'color'
  body_text_color:
    client: true
    refresh: true
    default: "#ffffff"
    type: 'color'
  header_background_color:
    client: true
    refresh: true
    default: "#000000"
    type: 'color'
  base_font_family:
    client: true
    refresh: true
    default: Jost*
  header_font_family:
    client: true
    refresh: true
    default: Jost*
  primary_color:
    client: true
    refresh: true
    default: "#181818FF"
    type: 'color'
  secondary_color:
    client: true
    refresh: true
    default: "#181818FF"
    type: 'color'
  tertiary_color:
    client: true
    refresh: true
    default: "#181818FF"
    type: color
  quaternary_color:
    client: true
    refresh: true
    default: rgba(255, 255, 255, 0.2)
    type: color
developer:
  enable_js_error_reporting:
    client: true
    refresh: true
    default: true
    type: 'boolean'
experimental:
  enable_web_updater:
    client: true
    refresh: true
    default: false
    type: 'boolean'
  external_stylesheets:
    client: true
    refresh: true
    default: https://fonts.cdnfonts.com/css/jost
    type: 'list'
  external_scripts:
    client: true
    refresh: true
    default: ""
    type: 'list'
