---
general:
  site_name:
    client: true
    exposed_to_client: true
    refresh: true
    default: CinelarTV
    min: 1
    max: 50
    regex: ^[a-zA-Z0-9 ]*$
  site_logo:
    client: true
    refresh: true
    default: /assets/default/cinelartv_default_logo.svg
    type: 'upload'
  site_description:
    client: true
    refresh: true
    default: CinelarTV
    min: 1
    max: 50
    regex: ^[a-zA-Z0-9 ]*$
  default_locale:
    client: true
    refresh: true
    default: es
    validator: "AllowedValuesValidator"
    type: 'enum'
    allowed_values:
      - en
      - es
      - pt
  enable_splash_screen:
    client: true
    refresh: true
    default: true
    type: 'boolean'
  allow_registration:
    client: true
    refresh: true
    default: true
    type: 'boolean'
  base_url:
    client: true
    refresh: true
    readonly: true,
    hidden: true
content:
  tmdb_api_key:
    client: true
    refresh: true
    default: ""
    type: 'string'
    secret: true
  
storage:
  allow_video_direct_link:
    client: true
    refresh: true
    default: false
    type: 'boolean'


customization:
  enable_carousel:
    client: true
    refresh: true
    default: true
    type: 'boolean'
  homescreen_cards_style:
    client: true
    refresh: true
    default: "CinelarTV"
    type: 'enum'
    allowed_values:
      - poster
      - backdrop
      - CinelarTV
      - custom_html
  homescreen_cards_custom_html:
    client: true
    refresh: true
    default: ""
    type: 'code'
  background_color:
    client: true
    refresh: true
    default: "#000000"
    type: 'color'
  body_text_color:
    client: true
    refresh: true
    default: "#ffffff"
    type: 'color'
  header_background_color:
    client: true
    refresh: true
    default: "#000000"
    type: 'color'
  base_font_family:
    client: true
    refresh: true
    default: Jost*
  header_font_family:
    client: true
    refresh: true
    default: Jost*
  primary_color:
    client: true
    refresh: true
    default: "#181818FF"
    type: 'color'
  secondary_color:
    client: true
    refresh: true
    default: "#181818FF"
    type: 'color'
  tertiary_color:
    client: true
    refresh: true
    default: "#181818FF"
    type: color
  quaternary_color:
    client: true
    refresh: true
    default: rgba(255, 255, 255, 0.2)
    type: color
developer:
  enable_js_error_reporting:
    client: true
    refresh: true
    default: true
    type: 'boolean'
experimental:
  enable_web_updater:
    client: true
    refresh: true
    default: false
    type: 'boolean'
  external_stylesheets:
    client: true
    refresh: true
    default: https://fonts.cdnfonts.com/css/jost
    type: 'list'
  external_scripts:
    client: true
    refresh: true
    default: ""
    type: 'list'
