name: "CinelarTV CI"
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Localazy Upload
        uses: localazy/upload@v1
        with:
          read_key: ${{ secrets.LOCALAZY_READ_KEY }}
          write_key: ${{ secrets.LOCALAZY_WRITE_KEY }}
        continue-on-error: true

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Set up database schema
        run: bundle exec rails db:migrate

      - name: Run tests
        run: bundle exec rspec

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install bundler-audit
        run: gem install bundler-audit

      - name: Security audit dependencies
        run: bundle audit check --ignore CVE-2015-9284 --update

      - name: Security audit application code
        run: bundle exec brakeman --no-exit-on-error --skip-files lib/cinelar_tv.rb,lib/updater.rb


  deploy:
    runs-on: ubuntu-latest
    needs: [test]  # Espera a que la tarea de "test" se complete con éxito
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create or switch to test-passed branch
        run: |
          # Cambiar a la rama "test-passed" si existe, o crearla si no existe
          git checkout -B test-passed origin/test-passed || git checkout -b test-passed
          
          # Forzar la actualización de la rama "test-passed" con el contenido de la rama "main"
          git reset --hard origin/main
          
          # Publicar la rama "test-passed" en el repositorio remoto
          git push -f origin test-passed

